apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
configMapGenerator:
  - name: embeddings-hotfix
    namespace: rag-kubernetes-search
    files:
      - embeddings.py=config/embeddings.py
      - main.py=config/main.py
