apiVersion: v1
kind: Service
metadata:
  name: rag-kubernetes-search
  namespace: rag-kubernetes-search
  labels:
    app: rag-kubernetes-search
spec:
  type: NodePort
  selector:
    app: rag-kubernetes-search
  ports:
    - name: http
      port: 8000
      targetPort: http
