apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rag-kubernetes-search
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/kmc-1234/Rag-Kubernetes-Search.git
    targetRevision: main
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: rag-kubernetes-search
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
